RISK_KEYWORDS = [
    "risk",
    "uncertainty",
    "volatile",
    "volatility",
    "inflation",
    "decline",
    "decrease",
    "pressure",
    "headwind",
    "weakness",
    "challenge",
    "litigation",
    "regulation",
    "disruption",
    "loss",
    "negative",
    "adverse",
    "constrained",
    "flat",
    "foreign exchange",
    "hedging",
    "slowdown",
    "cautious",
]